e-Spirit/javascript-content-api-library

src/modules/XMLParser.ts, src/types.ts
This PR relates to #8 and fixes the incorrect mapping for the div tag
=> fix(xml-parser): map div tag to block type

src/modules/CaaSMapper.ts, src/types.ts
Media entries of type FILE are explicitly mapped
remark: The change from d85f2e71f6 is not sufficient, since in resolveReferences the item is looked up by "id", which doesn't exist on CaaS items.
return {...item, id: item.identifier}
instead of
return item
would presumably work as well and could maybe added additionally as a fallback?
=> fix(caasmapper): map FILE entries

src/modules/FSXAApi.ts
We have fixed the issue that the user had to stringify the keys if only
an object was passed. Now the FSXA-Api does that directly.
=> fix: 🐛 fixed additionalParams for fetchByFilter

src/modules/CaaSMapper.ts, src/types.ts
=> feat(custom mapper): simplify custom mapper usage

src/integrations/express.ts
In the express.ts file is an error message for the missing locale. This message is misleading and
changed, because a request otherwise throw an bad request error.
=> fix(express.ts): fix the body request locale error message

src/integrations/express.ts
Change the express router method and replace "bodyparser.json" to "express.json" because the
bodyparser method was deprecated.
=> fix(express.ts): fix the deprecated express method

.gitignore, README.md, dev/index.ts, dev/utils.ts, package-lock.json, package.json, src/__tests__/integrations/express.spec.ts, src/__tests__/modules/FSXAApi.spec.ts, src/integrations/express.ts, src/modules/CaaSMapper.ts, src/modules/FSXAApi.ts, src/routes.ts, src/types.ts, src/utils.ts
This feature enables the use of remote media. 
However, it is only possible to use this feature if at least version **2021-06** is installed on the FirstSpirit server.
A new variable must be specified in the environment variables so that the remote project is registered. 
This is JSON which contains the name of the project as the key and the project ID as the value. Multiple projects can also be specified here.
If an element is requested via `fetchElement` or `fetchByFilter` and an element contains a remote medium, this remote medium is resolved and all available resolutions are available. 
If you want to access a remote medium directly, the methods `fetchElement` and `fetchByFilter` offer the possibility to enter the project name to access the medium.
This all is documented in the …
=> feat: enabled usage of remote media

src/modules/CaaSMapper.ts, src/types.ts
Added (optional) type names to interfaces used by CaaSMapper.
Since Types are not existent at runtime, those typenames enable easy differentiation of interfaces at runtime
=> feat(caasmapper): added type names to interfaces used by mapper

src/__tests__/modules/XMLParser.spec.ts, src/modules/XMLParser.ts
Link data containing ampersand, double quotes, or lower sign broke rich-text parsing
=> fixed handling of rich-text with special characters

CHANGELOG.md, src/modules/CaaSMapper.ts, src/types.ts
Added new default behavior that adds the revision of a medium to its url. Also added the
possibility to overwrite this behavior with a CustomMapper. Please read the update notice for
further details.
=> feat(caasmapper): add customizable media url builder, to add revision in preview mode

CHANGELOG.md, src/integrations/express.spec.ts, src/modules/CaaSMapper.ts, src/modules/FSXAProxyApi.spec.ts, src/modules/FSXAProxyApi.ts, src/modules/FSXARemoteApi.spec.ts, src/modules/FSXARemoteApi.ts, src/modules/XMLParser.ts, src/types.ts
fetchByFilter got an extended response structure
BREAKING CHANGE: Previously fetchByFilter directly returned an array of returned items. Now this
data is wrapped in an 'items' property. The returned object also includes pagination data now.
=> feat: update response structure of fetchByFilter

src/modules/CaaSMapper.spec.ts, src/modules/CaaSMapper.ts, src/testutils/createImageMap.ts, src/types.ts
To check for types at runtime, explicit type information must be carried within the object.
BREAKING CHANGE: Added type attribute needs to be added if objects of changed interfaces are created
in user code
=> feat(runtime types): add type attributes to interfaces and CaasMapper

src/modules/FSXAProxyApi.ts, src/types.ts
Client and server get seperate urls for api calls
=> refactor(api-config): update FSXAProxyApiConfig type

CHANGELOG.md, dev/utils.ts, src/modules/CaaSMapper.ts, src/types.ts
* feat(caas-mapper): map (nested) `Link`s in `RichTextElement`s
Links inside of RichtTextElements will now be mapped in the same way as the value of CMS_INPUT_LINK
BREAKING CHANGE: The structure of the CaasMapper output for Links in RichTextElements has been
updated
=> feat(caas-mapper): mapped links in doms (#81)

src/integrations/express.ts, src/modules/CaaSMapper.spec.ts, src/modules/CaaSMapper.ts, src/modules/FSXARemoteApi.spec.ts, src/modules/FSXARemoteApi.ts, src/types.ts
Fix hidden breaking change:
Remote Config only worked if the remoteName was matching the id
```
{
'remoteName': {
id: 'xxxx'
locale: 'de_DE'
}
}
```
=> Tng 1231 fix remotes

integrationtests/FSXAProxyApi.test.ts, src/modules/CaaSMapper.ts, src/modules/FSXAProxyApi.spec.ts, src/modules/FSXAProxyApi.ts, src/modules/FSXARemoteApi.spec.ts, src/modules/FSXARemoteApi.ts, src/modules/MappingUtils.ts, src/testutils/generateRandomConfig.ts, src/testutils/getMappedMediaPicture.ts
When requesting Remote items directly (opposed to indirectly as reference of another requested local
item), those remote items were not correctly handled. 
This led to empty responses, even though the item itself was correctly fetched and put
=> fix(remoteitems): fix direct request of remote items 

integrationtests/FSXAProxyApi.test.ts, src/modules/CaaSMapper.ts, src/modules/FSXAProxyApi.spec.ts, src/modules/FSXAProxyApi.ts, src/modules/FSXARemoteApi.spec.ts, src/modules/FSXARemoteApi.ts, src/modules/MappingUtils.ts, src/testutils/generateRandomConfig.ts, src/testutils/getMappedMediaPicture.ts
* fix(remoteitems): fix direct request od remote items
When requesting Remote items directly (opposed to indirectly as reference of another requested local item), those remote items were not correctly handled. 
This led to empty responses, even though the item itself was correctly fetched and put into resolvedReferences
=> fix(remoteitems): fix direct request of remote items  (#191)

src/modules/CaaSMapper.ts
Mark items that are being fetched as processed. Otherwise, items are fetched multiple times because of async race conditions.
=> fix(mapper): mark items that are being fetched as processed

src/modules/CaaSMapper.ts
Mark items that are being fetched as processed. Otherwise, items are fetched multiple times because of async race conditions.
=> fix(mapper): mark items that are being fetched as processed (#198)

src/modules/QueryBuilder.spec.ts, src/modules/QueryBuilder.ts, src/types.ts
This PR allow the user to skip the javascript regex validation for filters. Filters in the ContentAPI are not necessarily compatible with JavaScript Regex. For example `(?i).*example.*` works in ContentAPI but not in JavaScript.
=> Make regex validation filter optional
